POST http://localhost:8081/auth/connexion
Content-Type: application/json

{
  "email": "root@root.com",
  "motDePasse": "root"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    if(response.status === 200) {
        client.global.set("accessToken", response.headers.valueOf("Authorization").slice(7));
    }
%}

### create panier

POST http://localhost:8080/paniers
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

{
  "id" : 1,
  "couleur_choisi" : "ROUGE",
  "quantite" : 3
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
    if(response.status === 201) {
        client.global.set("token", response.body.token);
    }
%}

### get panier

GET http://localhost:8080/paniers/{{token}}
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### add produit panier

POST http://localhost:8080/paniers/{{token}}
Content-Type: application/json

{
  "id" :2,
  "couleur_choisi" : "bleu",
  "quantite" : 5
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### update produit panier

PUT http://localhost:8080/paniers/{{token}}/produits/2
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

{
  "couleur_choisi" : "bleu",
  "quantite" : 2
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### produit inconnue

PUT http://localhost:8080/paniers/{{token}}/produits/2
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

{
  "couleur_choisi" : "jaune",
  "quantite" : 2
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}

### Supprimer un produit
DELETE http://localhost:8080/paniers/{{token}}/produits/2/couleurs/bleu
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}

### Supprimer un panier
DELETE http://localhost:8080/paniers/{{token}}
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}

### create panier

POST http://localhost:8080/paniers
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

{
  "id" : 1,
  "couleur_choisi" : "ROUGE",
  "quantite" : 3
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
    if(response.status === 201) {
        client.global.set("token", response.body.token);
    }
%}

### valider panier : déconnecté

POST http://localhost:8080/paniers/{{token}}/valider_commande
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 401, "Response status is not 401");
    });
%}

### valider panier

POST http://localhost:8080/paniers/{{token}}/valider_commande
Content-Type: application/json
Authorization: Bearer {{accessToken}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### get All Commandes

GET http://localhost:8080/gestionnaires/commandes
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### modifier l'état d'une commande (à la main seulement)

PUT http://localhost:8080/gestionnaires/commandes/65f210e0d838327403638d40/livraison
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "etat_livraison": "LIVRE"
}

### get Commandes By ID

GET http://localhost:8080/gestionnaires/commandes/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### get All Commandes Utilisateur

GET http://localhost:8080/commandes
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### get Commande Utilisateur by ID

GET http://localhost:8080/commandes/65f1d43ee9a1f71e5e660593
Content-Type: application/json
Authorization: Bearer {{accessToken}}
